modLoader = "javafml"
loaderVersion = "[44,)"
license = "MIT"
issueTrackerURL="https://github.com/whizvox/Precision-Enchanter/issues"
[[mods]]
modId = "precisionenchanter"
version = "${file.jarVersion}"
displayName = "Precision Enchanter"
updateJSONURL="https://raw.githubusercontent.com/whizvox/Precision-Enchanter/main/updates.json"
displayURL="http://github.com/whizvox/Precision-Enchanter"
logoFile="precisionenchanter-logo.png"
authors = "whizvox"
description = '''
Have more control over enchanting! Remove the randomness by crafting and removing specific enchantments.
'''

[[dependencies.precisionenchanter]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.precisionenchanter]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4,1.20)"
ordering = "NONE"
side = "BOTH"
